apiVersion: apps/v1
kind: Deployment

metadata:
  name: pythontest
  labels:
    app: pythontest

spec:
  replicas: 1

  selector:
    matchLabels:
      app: pythontest

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: pythontest

    spec:
      containers:
      - name: pythontest

        image: 172.20.0.2:4000/pythontest:latest

        imagePullPolicy: Always

        ports:
        - name: microport
          containerPort: 5000